version : "3"

services:
  
  webapi :
    build :
      context : ./ProjectRenamer
      dockerfile : Dockerfile
    image : projectrenamer-api
    expose :
      - 80
    restart: always

  lb:
    image: dockercloud/haproxy:1.6.7
    links:
      - webapi
    ports:
      - 8081:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  webui : 
    build : 
      context : ./projectrenamer-ui
      dockerfile : Dockerfile
    image : projectrenamer-ui
    ports :
      - 8080:80