CREATE TABLE UserClaims
(
  Id               BIGINT AUTO_INCREMENT PRIMARY KEY,
  UserId           BIGINT NOT NULL,
  UserRoleId       BIGINT NOT NULL,
  IsDeleted        BIT    NOT NULL DEFAULT 0,
  UpdateDate       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CreateDate       DATETIME DEFAULT CURRENT_TIMESTAMP
);