CREATE TABLE UserRoles
(
  Id               BIGINT AUTO_INCREMENT PRIMARY KEY,
  RoleName         VARCHAR(20) NOT NULL,
  Explanation      LONGTEXT,
  IsDeleted        BIT         NOT NULL DEFAULT 0,
  UpdateDate       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CreateDate       DATETIME DEFAULT CURRENT_TIMESTAMP
);