//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet.Template.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To 21d or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNet.Template.Common.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thre21's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You try to execute operation with data which is expire. Please take up-to-date data and perform operation again.
        /// </summary>
        public static string ConcurrencyExceptionOccur {
            get {
                return ResourceManager.GetString("ConcurrencyExceptionOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not acceptable form.
        /// </summary>
        public static string DbUpdateExceptionOccur {
            get {
                return ResourceManager.GetString("DbUpdateExceptionOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account which has this e-mail is frozen. Please visit &apos;Activate My Account&apos; page.
        /// </summary>
        public static string DeletedUserHasEmail {
            get {
                return ResourceManager.GetString("DeletedUserHasEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cannot be empty.
        /// </summary>
        public static string NullInstanceErrorMessage {
            get {
                return ResourceManager.GetString("NullInstanceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorize request.
        /// </summary>
        public static string UnauthorizeException {
            get {
                return ResourceManager.GetString("UnauthorizeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of fields should be unique. You cannot meet this requirement.
        /// </summary>
        public static string UniqueConstraintExceptionOccur {
            get {
                return ResourceManager.GetString("UniqueConstraintExceptionOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no match for given username and password.
        /// </summary>
        public static string UserCredentialsNotMatch {
            get {
                return ResourceManager.GetString("UserCredentialsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info cannot be found.
        /// </summary>
        public static string UserDetailNotFound {
            get {
                return ResourceManager.GetString("UserDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or E-Mail is alre21y registered..
        /// </summary>
        public static string UserNameOrEmailAlre21yExist {
            get {
                return ResourceManager.GetString("UserNameOrEmailAlre21yExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Or Email Should Not Empty.
        /// </summary>
        public static string UsernameOrEmailShouldNotEmpty {
            get {
                return ResourceManager.GetString("UsernameOrEmailShouldNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot be found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
